name: flutter_html_to_pdf_v2
description: A Flutter plugin to convert HTML content to PDF files with proper support for complex scripts like Khmer, Thai, Arabic, etc.
version: 1.0.1
homepage: https://github.com/puthsokha/flutter_html_to_pdf_v2
repository: https://github.com/puthsokha/flutter_html_to_pdf_v2
issue_tracker: https://github.com/puthsokha/flutter_html_to_pdf_v2/issues

environment:
  sdk: ^3.10.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_html_to_pdf_v2
        pluginClass: FlutterHtmlToPdfPlugin
      ios:
        pluginClass: FlutterHtmlToPdfPlugin
